// Re-exports each module's schema. New modules add `export * from "@/modules/<name>/schema"` here.

export * from "@/modules/auth/schema"
export * from "@/modules/audit/schema"
export * from "@/modules/items/schema"
export * from "@/modules/files/schema"
export * from "@/modules/terminology/schema"
export * from "@/modules/custom-fields/schema"
export * from "@/modules/rbac/schema"
export * from "@/modules/companies/schema"
export * from "@/modules/contacts/schema"
export * from "@/modules/pipelines/schema"
export * from "@/modules/projects/schema"
export * from "@/modules/opportunities/schema"
export * from "@/modules/tasks/schema"
export * from "@/modules/project-templates/schema"
export * from "@/modules/saved-views/schema"
export * from "@/modules/invoices/schema"
